[project]
name = "glowing-memory"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "aiohttp",
    "resend",
    "newspaper3k",
    "mistralai",
    "lxml-html-clean",
]

[dependency-groups]
dev = [
    "ruff>=0.15.1",
    "ty>=0.0.17",
]
